# Generated by Django 4.0 on 2021-12-22 13:35

import controller.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(upload_to=controller.models.user_directory_path, verbose_name='Воспоминания'),
        ),
    ]
