# Generated by Django 4.0 on 2021-12-22 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('controller', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='memories',
        ),
    ]
